<a href="https://colab.research.google.com/github/abhi1628/Python_Training/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
a = numpy.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.size)
print(a.shape)
print(type(a))

[1 2 3 4 5 6 7 8 9]
9
(9,)
<class 'numpy.ndarray'>


In [2]:
a = numpy.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.size)
print(a.shape)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
<class 'numpy.ndarray'>


In [3]:
a = numpy.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a = numpy.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a.itemsize) # gives the size of element in bytes

8


In [8]:
a = numpy.array([(1,2,3),(4,5,6)])
print('Before Reshaping:')
print(a)
print('The dimensions are:', a.shape)
a = a.reshape(3,2)
print('After Reshaping:')
print(a)
print('The dimensions are:', a.shape)

Before Reshaping:
[[1 2 3]
 [4 5 6]]
The dimensions are: (2, 3)
After Reshaping:
[[1 2]
 [3 4]
 [5 6]]
The dimensions are: (3, 2)


In [12]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
a = np.arange(6).reshape(2,3) # another way to write matrix
print(a)

[[0 1 2]
 [3 4 5]]


In [15]:
from numpy import array
a = array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a = np.arange(6).reshape(3,3) # another way to write matrix
print(a)

ValueError: ignored

In [17]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
a = np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
a = np.array([[67, 19], [39, 13]])
d = np.linalg.det(a)
print(d)

129.99999999999986


In [25]:
a = np.array([[67, 19], [39, 13]])
d = np.linalg.inv(a)
print(d)

[[ 0.1        -0.14615385]
 [-0.3         0.51538462]]


## If an array has a very small or very large determinant, then a call to det may overflow or underflow. numpy.linalg.slogdet is more robust against such issues, because it computes the logarithm of the determinant rather than the determinant itself.

In [26]:
a = np.array([[67, 19], [39, 13]])
(sign, logdet) = np.linalg.slogdet(a)
print(sign, logdet)
d = sign * np.exp(logdet)
print(d)

1.0 4.867534450455581
129.99999999999986


## Most Imp Concept to be used in ML

In [27]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a.sum(axis = 0))

[12 15 18]


In [28]:
print(a.sum(axis = 1))

[ 6 15 24]


## Flattening arrays

In [29]:
a = np.array([[0,1], [2,3]])
b = a.flatten()
print(b)
b[0] = 10
print('The array b is:',b)
print('The array a is:',a)

[0 1 2 3]
The array b is: [10  1  2  3]
The array a is: [[0 1]
 [2 3]]


In [30]:
a = np.array([[0,1], [2,3]])
b = a.ravel()
print(b)
b[0] = 10
print('The array b is:',b)
print('The array a is:',a)

[0 1 2 3]
The array b is: [10  1  2  3]
The array a is: [[10  1]
 [ 2  3]]


## Some imp operations

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a - b)

[-3 -3 -3]


In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)

[ 4 10 18]


In [38]:
a = np.array([np.arange(0,3), np.arange(0,6)])
b = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
print('Matrix a is:',a)
print('Matrix b is:',b)
print('Scalar Product is:', a * 2)
print('Dot Product:', np.dot(a, b))

Matrix a is: [array([0, 1, 2]) array([0, 1, 2, 3, 4, 5])]
Matrix b is: [[0 1]
 [2 3]
 [4 5]]
Scalar Product is: [array([0, 2, 4]) array([ 0,  2,  4,  6,  8, 10])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


ValueError: ignored

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
print(a + b)

ValueError: ignored

## Broadcast

In [41]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
b = np.array([1,2,3])
c = np.array([10, 20])
print(a.shape, b.shape, c.shape)
print(a + c)

[[1 2]
 [3 4]
 [5 6]]
(3, 2) (3,) (2,)
[[11 22]
 [13 24]
 [15 26]]


In [42]:
print(a + b)

ValueError: ignored

## 1. size of each dimensions should be same
## 2. size of one of the dimension should be 1